NAME := $(shell basename $(shell git config --get remote.origin.url) | sed 's/\.git//')
BRANCH := $(shell git symbolic-ref --short HEAD 2>/dev/null)
VERSION := $(shell git log -1 --pretty=format:"%H")
FEVERSION := $(shell date +'%Y%m%d%H%M%S')
TMPDIR=kaoqin-hr-ke-com
RELEASESDIR=releases

default: all

all: pack

test: init
	echo "$(VERSION)" > $(TMPDIR)/VERSION

init: clean
	mkdir -p $(TMPDIR)
pack: init
	echo "$(VERSION)" > $(TMPDIR)/VERSION

	sh online.sh


	(cd server && cp -r bin dist node_modules package.json ../$(TMPDIR))
	(cd client && cp -R ./dist/*  ../$(TMPDIR)/dist/statics)

	mkdir -p $(RELEASESDIR)
	tar czf $(RELEASESDIR)/$(TMPDIR).tar.gz $(TMPDIR)/

clean:
	rm -rf $(TMPDIR)
	rm -rf $(RELEASESDIR)

.DEFAULT: all
